import type { ScriptableWidgetFamily, ScriptableWidgetType } from './model';

export const SCRIPTABLE_DATA_BOOKMARK_NAME = 'Routine Streaks Data';

export interface ScriptableWidgetCodeOptions {
	widgetType: ScriptableWidgetType;
	routineId: string;
	widgetFamily: ScriptableWidgetFamily;
	todayRoutineIds: string[];
}

export function createScriptableWidgetCode(
	dataJsonPath: string,
	options: ScriptableWidgetCodeOptions = {
		widgetType: 'dashboard',
		routineId: '',
		widgetFamily: 'large',
		todayRoutineIds: [],
	},
): string {
	const dataJsonPathLiteral = JSON.stringify(dataJsonPath);
	const widgetTypeLiteral = JSON.stringify(options.widgetType);
	const routineIdLiteral = JSON.stringify(options.routineId);
	const widgetFamilyLiteral = JSON.stringify(options.widgetFamily);
	const todayRoutineIdsLiteral = JSON.stringify(options.todayRoutineIds);

	return [
		'// Routine Streaks - Scriptable iPhone widget',
		'//',
		'// Setup:',
		'// 1. In Scriptable, open Settings > File Bookmarks.',
		`// 2. Add a bookmark named "${SCRIPTABLE_DATA_BOOKMARK_NAME}".`,
		'// 3. Point it to your vault file:',
		`//    ${dataJsonPath}`,
		'// 4. Paste this script into Scriptable and add it as a widget.',
		`// Generated display: ${options.widgetType}`,
		`// Generated widget size: ${options.widgetFamily}`,
		'',
		`const DATA_BOOKMARK_NAME = "${SCRIPTABLE_DATA_BOOKMARK_NAME}";`,
		`const GENERATED_WIDGET_TYPE = ${widgetTypeLiteral};`,
		`const GENERATED_ROUTINE_ID = ${routineIdLiteral};`,
		`const GENERATED_WIDGET_FAMILY = ${widgetFamilyLiteral};`,
		`const GENERATED_TODAY_ROUTINE_IDS = ${todayRoutineIdsLiteral};`,
		'let FAMILY = "medium";',
		'let MAX_ROUTINES = 4;',
		'let MAX_TASKS = 5;',
		'',
		'function normalizeFamily(family) {',
		'  if (family === "small" || family === "medium" || family === "large") return family;',
		'  if (family === "accessoryRectangular" || family === "accessoryInline" || family === "accessoryCircular") return "small";',
		'  return "medium";',
		'}',
		'',
		'function setFamily(family) {',
		'  FAMILY = normalizeFamily(family);',
		'  MAX_ROUTINES = FAMILY === "large" ? 8 : FAMILY === "small" ? 2 : 4;',
		'  MAX_TASKS = FAMILY === "large" ? 8 : FAMILY === "small" ? 2 : 5;',
		'}',
		'',
		'setFamily(config.runsInWidget ? config.widgetFamily || GENERATED_WIDGET_FAMILY : GENERATED_WIDGET_FAMILY);',
		'',
		'const COLORS = {',
		'  backgroundTop: "#111827",',
		'  backgroundBottom: "#24213f",',
		'  card: "#1f2937",',
		'  text: "#f9fafb",',
		'  muted: "#9ca3af",',
		'  faint: "#6b7280",',
		'  success: "#86efac",',
		'  warning: "#fca5a5",',
		'  accent: "#fbbf24",',
		'  line: "#374151",',
		'};',
		'',
		'const PET_COLORS = {',
		'  blush: "#f49ab0",',
		'  cat: "#8f9aa7",',
		'  catDark: "#687482",',
		'  dog: "#c78342",',
		'  dogDark: "#90572d",',
		'  eye: "#211b18",',
		'  mouth: "#211b18",',
		'  muzzle: "#f1d2a2",',
		'  outline: "#2a2522",',
		'  parrot: "#38b96d",',
		'  parrotDark: "#1f7d45",',
		'  parrotLight: "#8de88d",',
		'  parrotWing: "#2374c6",',
		'  beak: "#f2b33d",',
		'  warning: "#d94b45",',
		'  white: "#fff2d8",',
		'};',
		'',
		'async function readRoutineSettings() {',
		'  const fm = FileManager.iCloud();',
		'',
		'  if (!fm.bookmarkExists(DATA_BOOKMARK_NAME)) {',
		'    return {',
		'      error: "Create a Scriptable file bookmark named \\"" + DATA_BOOKMARK_NAME + "\\" that points to " + ' +
			dataJsonPathLiteral +
			' + ".",',
		'    };',
		'  }',
		'',
		'  const path = fm.bookmarkedPath(DATA_BOOKMARK_NAME);',
		'',
		'  try {',
		'    if (typeof fm.isFileStoredIniCloud === "function" && fm.isFileStoredIniCloud(path)) {',
		'      await fm.downloadFileFromiCloud(path);',
		'    }',
		'  } catch (error) {',
		'    // The file may already be local or the method may be unavailable.',
		'  }',
		'',
		'  try {',
		'    const settings = JSON.parse(fm.readString(path));',
		'    return normalizeExportedSettings(settings);',
		'  } catch (error) {',
		'    return { error: "Could not read Routine Streaks data.json: " + error };',
		'  }',
		'}',
		'',
		'function normalizeExportedSettings(settings) {',
		'  if (!settings || typeof settings !== "object") return { routines: [], cache: {} };',
		'  return settings;',
		'}',
		'',
		'function readNumber(value, fallback) {',
		'  const number = Number(value);',
		'  return Number.isFinite(number) ? number : fallback;',
		'}',
		'',
		'function exportedTodaySummary(settings) {',
		'  const summary = settings.todaySummary || {};',
		'  const requiredRoutineIds = Array.isArray(summary.requiredRoutineIds) ? summary.requiredRoutineIds : [];',
		'  const completedRoutineIds = Array.isArray(summary.completedRoutineIds) ? summary.completedRoutineIds : [];',
		'  const incompleteRoutineIds = Array.isArray(summary.incompleteRoutineIds) ? summary.incompleteRoutineIds : [];',
		'  const requiredCount = readNumber(summary.required, requiredRoutineIds.length);',
		'  const completedCount = readNumber(summary.completed, completedRoutineIds.length);',
		'  const incompleteCount = readNumber(summary.incomplete, incompleteRoutineIds.length);',
		'  return {',
		'    requiredRoutineIds: requiredRoutineIds,',
		'    completedRoutineIds: completedRoutineIds,',
		'    incompleteRoutineIds: incompleteRoutineIds,',
		'    requiredCount: requiredCount,',
		'    completed: completedCount,',
		'    incomplete: incompleteCount,',
		'    allDone: summary.allDone === true,',
		'    bestCurrentStreak: readNumber(summary.bestCurrentStreak, readNumber(settings.bestCurrentStreak, 0)),',
		'  };',
		'}',
		'',
		'function cacheFor(settings, routine) {',
		'  return (settings.cache && settings.cache[routine.id]) || {};',
		'}',
		'',
		'function exportedRoutineSummary(settings, routine) {',
		'  const summary = settings.todaySummary || {};',
		'  const routines = Array.isArray(summary.routines) ? summary.routines : [];',
		'  return routines.find(function (candidate) {',
		'    return candidate && candidate.id === routine.id;',
		'  }) || {};',
		'}',
		'',
		'function weeklyProgressLabel(settings, routine) {',
		'  const summary = exportedRoutineSummary(settings, routine);',
		'  if (summary.progressKind !== "weekly_count") return "";',
		'  if (typeof summary.progressLabel === "string" && summary.progressLabel.length > 0) return summary.progressLabel;',
		'  const completed = readNumber(summary.weeklyCompleted, readNumber(summary.progressCompleted, 0));',
		'  const target = readNumber(summary.weeklyTarget, readNumber(summary.progressTarget, 0));',
		'  return target > 0 ? completed + "/" + target + " this week" : "";',
		'}',
		'',
		'function routineProgressLabel(settings, routine, cache) {',
		'  const weeklyLabel = weeklyProgressLabel(settings, routine);',
		'  if (weeklyLabel.length > 0) return weeklyLabel;',
		'  const taskCount = Number(cache.todayTaskCount || 0);',
		'  const completedCount = Number(cache.todayCompletedTaskCount || 0);',
		'  return taskCount > 0 ? completedCount + "/" + taskCount + " tasks" : "No tasks";',
		'}',
		'',
		'function routineStatusPillLabel(settings, routine, cache) {',
		'  const weeklyLabel = weeklyProgressLabel(settings, routine);',
		'  return weeklyLabel.length > 0 ? weeklyLabel : statusLabel(cache.todayStatus);',
		'}',
		'',
		'function routineScheduleTypeLabel(settings, routine) {',
		'  const summary = exportedRoutineSummary(settings, routine);',
		'  if (typeof summary.scheduleTypeLabel === "string" && summary.scheduleTypeLabel.length > 0) return summary.scheduleTypeLabel;',
		'  const type = routine && routine.schedule ? routine.schedule.type : "weekdays";',
		'  if (type === "weekly_count") return "Weekly";',
		'  if (type === "interval") return "Interval";',
		'  return "Weekdays";',
		'}',
		'',
		'function enabledRoutines(settings) {',
		'  return (settings.routines || []).filter(function (routine) {',
		'    return routine.enabled !== false;',
		'  });',
		'}',
		'',
		'function requiredToday(settings, routines) {',
		'  const ids = exportedTodaySummary(settings).requiredRoutineIds;',
		'  return ids.map(function (id) {',
		'    return routines.find(function (routine) {',
		'      return routine.id === id;',
		'    });',
		'  }).filter(Boolean);',
		'}',
		'',
		'function todaySummary(settings) {',
		'  const summary = exportedTodaySummary(settings);',
		'  return {',
		'    required: requiredToday(settings, enabledRoutines(settings)),',
		'    requiredCount: summary.requiredCount,',
		'    completed: summary.completed,',
		'    incomplete: summary.incomplete,',
		'    allDone: summary.allDone,',
		'  };',
		'}',
		'',
		'function bestCurrentStreak(settings) {',
		'  return exportedTodaySummary(settings).bestCurrentStreak;',
		'}',
		'',
		'function selectedWidgetType(settings) {',
		'  const type = GENERATED_WIDGET_TYPE || settings.scriptableWidgetType || "dashboard";',
		'  const allowed = ["dashboard", "overview", "pet", "routine_cards", "today_items", "routine_focus"];',
		'  return allowed.indexOf(type) >= 0 ? type : "dashboard";',
		'}',
		'',
		'function selectedRoutine(settings, routines) {',
		'  const id = GENERATED_ROUTINE_ID || settings.scriptableRoutineId || "";',
		'  return routines.find(function (routine) {',
		'    return routine.id === id;',
		'  }) || routines[0] || null;',
		'}',
		'',
		'function selectedTodayRoutines(settings, routines) {',
		'  const ids = GENERATED_TODAY_ROUTINE_IDS.length > 0 ? GENERATED_TODAY_ROUTINE_IDS : settings.scriptableTodayRoutineIds || [];',
		'  const selected = ids.map(function (id) {',
		'    return routines.find(function (routine) {',
		'      return routine.id === id;',
		'    });',
		'  }).filter(Boolean);',
		'  const fallback = requiredToday(settings, routines);',
		'  const source = selected.length > 0 ? selected : fallback;',
		'  const max = FAMILY === "small" ? 1 : 4;',
		'  return source.slice(0, max);',
		'}',
		'',
		'function statusLabel(status) {',
		'  if (status === "complete") return "Done";',
		'  if (status === "incomplete") return "Open";',
		'  if (status === "missing_daily_note") return "Missing note";',
		'  if (status === "no_tasks") return "No tasks";',
		'  if (status === "frozen") return "Frozen";',
		'  if (status === "off_schedule") return "Rest";',
		'  if (status === "stale") return "Needs sync";',
		'  return "Idle";',
		'}',
		'',
		'function statusColor(status) {',
		'  if (status === "complete") return COLORS.success;',
		'  if (status === "incomplete" || status === "missing_daily_note" || status === "no_tasks" || status === "stale") return COLORS.warning;',
		'  if (status === "frozen") return COLORS.accent;',
		'  return COLORS.faint;',
		'}',
		'',
		'function petMood(allDone) {',
		'  return allDone ? "happy" : "angry";',
		'}',
		'',
		'function createPetImage(pet, mood) {',
		'  const context = new DrawContext();',
		'  context.size = new Size(64, 64);',
		'  context.opaque = false;',
		'  context.respectScreenScale = false;',
		'',
		'  if (pet === "cat") {',
		'    drawCatPixelArt(context, mood);',
		'  } else if (pet === "parrot") {',
		'    drawParrotPixelArt(context, mood);',
		'  } else {',
		'    drawDogPixelArt(context, mood);',
		'  }',
		'',
		'  return context.getImage();',
		'}',
		'',
		'function addPetImage(container, settings, allDone, size) {',
		'  const pet = settings.overviewPet || "dog";',
		'  const image = container.addImage(createPetImage(pet, petMood(allDone)));',
		'  image.imageSize = new Size(size, size);',
		'  return image;',
		'}',
		'',
		'function drawDogPixelArt(context, mood) {',
		'  const angry = mood === "angry";',
		'  const c = PET_COLORS;',
		'',
		'  drawPixelRect(context, 10, 7, 12, 22, c.outline);',
		'  drawPixelRect(context, 12, 9, 8, 18, c.dogDark);',
		'  drawPixelRect(context, 42, 7, 12, 22, c.outline);',
		'  drawPixelRect(context, 44, 9, 8, 18, c.dogDark);',
		'  drawPixelRect(context, 20, 6, 24, 4, c.outline);',
		'  drawPixelRect(context, 16, 10, 32, 4, c.outline);',
		'  drawPixelRect(context, 12, 14, 40, 8, c.outline);',
		'  drawPixelRect(context, 10, 22, 44, 24, c.outline);',
		'  drawPixelRect(context, 14, 46, 36, 8, c.outline);',
		'  drawPixelRect(context, 20, 54, 24, 4, c.outline);',
		'  drawPixelRect(context, 20, 10, 24, 4, c.dog);',
		'  drawPixelRect(context, 16, 14, 32, 8, c.dog);',
		'  drawPixelRect(context, 14, 22, 36, 22, c.dog);',
		'  drawPixelRect(context, 18, 44, 28, 8, c.dog);',
		'  drawPixelRect(context, 24, 52, 16, 2, c.dog);',
		'  drawPixelRect(context, 20, 31, 24, 16, c.muzzle);',
		'  drawPixelRect(context, 24, 35, 16, 14, c.white);',
		'  drawPixelRect(context, 30, 34, 4, 4, c.eye);',
		'',
		'  if (angry) {',
		'    drawPixelRect(context, 21, 24, 9, 3, c.warning);',
		'    drawPixelRect(context, 35, 24, 9, 3, c.warning);',
		'    drawPixelRect(context, 21, 27, 5, 3, c.eye);',
		'    drawPixelRect(context, 39, 27, 5, 3, c.eye);',
		'    drawPixelRect(context, 25, 43, 14, 3, c.mouth);',
		'    drawPixelRect(context, 24, 44, 4, 3, c.mouth);',
		'    drawPixelRect(context, 36, 44, 4, 3, c.mouth);',
		'  } else {',
		'    drawPixelRect(context, 23, 25, 5, 5, c.eye);',
		'    drawPixelRect(context, 37, 25, 5, 5, c.eye);',
		'    drawPixelRect(context, 26, 43, 12, 3, c.mouth);',
		'    drawPixelRect(context, 28, 46, 8, 4, c.blush);',
		'  }',
		'',
		'  drawPixelRect(context, 16, 33, 4, 3, c.blush);',
		'  drawPixelRect(context, 44, 33, 4, 3, c.blush);',
		'  drawPixelRect(context, 20, 56, 6, 2, c.outline);',
		'  drawPixelRect(context, 38, 56, 6, 2, c.outline);',
		'}',
		'',
		'function drawCatPixelArt(context, mood) {',
		'  const angry = mood === "angry";',
		'  const c = PET_COLORS;',
		'',
		'  drawPixelRect(context, 8, 5, 6, 8, c.outline);',
		'  drawPixelRect(context, 14, 9, 6, 8, c.outline);',
		'  drawPixelRect(context, 50, 5, 6, 8, c.outline);',
		'  drawPixelRect(context, 44, 9, 6, 8, c.outline);',
		'  drawPixelRect(context, 10, 9, 4, 6, c.cat);',
		'  drawPixelRect(context, 48, 9, 4, 6, c.cat);',
		'  drawPixelRect(context, 12, 15, 40, 6, c.outline);',
		'  drawPixelRect(context, 10, 21, 44, 24, c.outline);',
		'  drawPixelRect(context, 14, 45, 36, 8, c.outline);',
		'  drawPixelRect(context, 20, 53, 24, 4, c.outline);',
		'  drawPixelRect(context, 16, 17, 32, 4, c.cat);',
		'  drawPixelRect(context, 14, 21, 36, 22, c.cat);',
		'  drawPixelRect(context, 18, 43, 28, 8, c.cat);',
		'  drawPixelRect(context, 24, 51, 16, 2, c.cat);',
		'  drawPixelRect(context, 21, 33, 22, 14, c.muzzle);',
		'  drawPixelRect(context, 25, 36, 14, 12, c.white);',
		'  drawPixelRect(context, 30, 34, 4, 4, c.eye);',
		'  drawPixelRect(context, 16, 20, 6, 3, c.catDark);',
		'  drawPixelRect(context, 42, 20, 6, 3, c.catDark);',
		'',
		'  if (angry) {',
		'    drawPixelRect(context, 21, 24, 9, 3, c.warning);',
		'    drawPixelRect(context, 35, 24, 9, 3, c.warning);',
		'    drawPixelRect(context, 21, 27, 5, 3, c.eye);',
		'    drawPixelRect(context, 39, 27, 5, 3, c.eye);',
		'    drawPixelRect(context, 25, 43, 14, 3, c.mouth);',
		'    drawPixelRect(context, 24, 44, 4, 3, c.mouth);',
		'    drawPixelRect(context, 36, 44, 4, 3, c.mouth);',
		'  } else {',
		'    drawPixelRect(context, 23, 25, 5, 5, c.eye);',
		'    drawPixelRect(context, 37, 25, 5, 5, c.eye);',
		'    drawPixelRect(context, 26, 43, 12, 3, c.mouth);',
		'    drawPixelRect(context, 28, 46, 8, 4, c.blush);',
		'  }',
		'',
		'  drawPixelRect(context, 6, 35, 12, 2, c.outline);',
		'  drawPixelRect(context, 46, 35, 12, 2, c.outline);',
		'  drawPixelRect(context, 7, 40, 11, 2, c.outline);',
		'  drawPixelRect(context, 46, 40, 11, 2, c.outline);',
		'  drawPixelRect(context, 16, 32, 4, 3, c.blush);',
		'  drawPixelRect(context, 44, 32, 4, 3, c.blush);',
		'}',
		'',
		'function drawParrotPixelArt(context, mood) {',
		'  const angry = mood === "angry";',
		'  const c = PET_COLORS;',
		'',
		'  drawPixelRect(context, 19, 7, 21, 4, c.outline);',
		'  drawPixelRect(context, 15, 11, 29, 8, c.outline);',
		'  drawPixelRect(context, 13, 19, 34, 15, c.outline);',
		'  drawPixelRect(context, 43, 21, 12, 7, c.outline);',
		'  drawPixelRect(context, 47, 28, 10, 5, c.outline);',
		'  drawPixelRect(context, 13, 34, 35, 18, c.outline);',
		'  drawPixelRect(context, 17, 52, 22, 6, c.outline);',
		'  drawPixelRect(context, 10, 45, 10, 15, c.outline);',
		'  drawPixelRect(context, 14, 58, 8, 4, c.outline);',
		'  drawPixelRect(context, 24, 58, 6, 3, c.outline);',
		'  drawPixelRect(context, 35, 58, 6, 3, c.outline);',
		'  drawPixelRect(context, 20, 11, 19, 4, c.parrotLight);',
		'  drawPixelRect(context, 17, 15, 25, 8, c.parrot);',
		'  drawPixelRect(context, 16, 23, 28, 10, c.parrot);',
		'  drawPixelRect(context, 17, 34, 27, 16, c.parrot);',
		'  drawPixelRect(context, 21, 50, 16, 4, c.parrotDark);',
		'  drawPixelRect(context, 12, 46, 8, 12, c.parrotDark);',
		'  drawPixelRect(context, 31, 34, 12, 16, c.parrotWing);',
		'  drawPixelRect(context, 34, 38, 8, 8, c.parrotDark);',
		'  drawPixelRect(context, 20, 18, 10, 10, c.white);',
		'  drawPixelRect(context, 23, 20, 4, 4, c.eye);',
		'',
		'  if (angry) {',
		'    drawPixelRect(context, 18, 16, 12, 3, c.warning);',
		'    drawPixelRect(context, 25, 18, 5, 3, c.warning);',
		'    drawPixelRect(context, 22, 21, 7, 3, c.eye);',
		'    drawPixelRect(context, 39, 19, 13, 5, c.outline);',
		'    drawPixelRect(context, 42, 23, 14, 4, c.outline);',
		'    drawPixelRect(context, 42, 31, 12, 5, c.outline);',
		'    drawPixelRect(context, 41, 20, 10, 3, c.beak);',
		'    drawPixelRect(context, 44, 24, 10, 2, c.beak);',
		'    drawPixelRect(context, 44, 28, 10, 4, c.mouth);',
		'    drawPixelRect(context, 43, 32, 9, 3, c.beak);',
		'  } else {',
		'    drawPixelRect(context, 40, 22, 10, 4, c.beak);',
		'    drawPixelRect(context, 45, 25, 10, 4, c.beak);',
		'    drawPixelRect(context, 47, 30, 7, 2, c.beak);',
		'    drawPixelRect(context, 43, 29, 8, 2, c.mouth);',
		'    drawPixelRect(context, 25, 46, 6, 3, c.blush);',
		'  }',
		'',
		'  drawPixelRect(context, 16, 30, 4, 3, c.blush);',
		'  drawPixelRect(context, 29, 55, 6, 3, c.parrotDark);',
		'}',
		'',
		'function drawPixelRect(context, x, y, width, height, color) {',
		'  context.setFillColor(new Color(color));',
		'  context.fillRect(new Rect(x, y, width, height));',
		'}',
		'',
		'function addText(container, value, font, color) {',
		'  const text = container.addText(String(value));',
		'  text.font = font;',
		'  text.textColor = new Color(color);',
		'  text.lineLimit = 1;',
		'  return text;',
		'}',
		'',
		'function setWidgetBackground(widget) {',
		'  const gradient = new LinearGradient();',
		'  gradient.locations = [0, 1];',
		'  gradient.colors = [new Color(COLORS.backgroundTop), new Color(COLORS.backgroundBottom)];',
		'  widget.backgroundGradient = gradient;',
		'}',
		'',
		'function addPill(container, label, color) {',
		'  const pill = container.addStack();',
		'  pill.backgroundColor = new Color(color, 0.16);',
		'  pill.cornerRadius = 8;',
		'  pill.setPadding(3, 8, 3, 8);',
		'  const text = addText(pill, label, Font.boldSystemFont(9), color);',
		'  text.minimumScaleFactor = 0.65;',
		'  return pill;',
		'}',
		'',
		'function addMetricCard(container, value, label, color, size) {',
		'  const card = container.addStack();',
		'  card.layoutVertically();',
		'  card.backgroundColor = new Color(COLORS.card, 0.78);',
		'  card.cornerRadius = 10;',
		'  if (size) card.size = size;',
		'  card.setPadding(8, 9, 8, 9);',
		'  addText(card, value, Font.heavySystemFont(18), color);',
		'  card.addSpacer(2);',
		'  addText(card, label, Font.boldSystemFont(9), COLORS.muted);',
		'  return card;',
		'}',
		'',
		'function addHeader(widget, settings, title, subtitle, allDone, showPet) {',
		'  const header = widget.addStack();',
		'  header.layoutHorizontally();',
		'  header.centerAlignContent();',
		'  const titleBlock = header.addStack();',
		'  titleBlock.layoutVertically();',
		'  addText(titleBlock, title, Font.boldSystemFont(14), COLORS.text);',
		'  addText(titleBlock, subtitle, Font.systemFont(10), allDone ? COLORS.success : COLORS.warning);',
		'  if (showPet !== false) {',
		'    header.addSpacer();',
		'    addPetImage(header, settings, allDone, 26);',
		'  }',
		'}',
		'',
		'function createBaseWidget(settings, title, subtitle, allDone, showHeaderPet) {',
		'  const widget = new ListWidget();',
		'  setWidgetBackground(widget);',
		'  widget.setPadding(14, 14, 14, 14);',
		'  widget.url = "obsidian://open";',
		'  addHeader(widget, settings, title, subtitle, allDone, showHeaderPet);',
		'  widget.addSpacer(10);',
		'  return widget;',
		'}',
		'',
		'function addHeroStreak(container, value, label, statusText, color) {',
		'  const hero = container.addStack();',
		'  hero.layoutHorizontally();',
		'  hero.bottomAlignContent();',
		'  hero.backgroundColor = new Color(COLORS.card, 0.58);',
		'  hero.cornerRadius = 12;',
		'  hero.setPadding(10, 12, 10, 12);',
		'  addText(hero, value, Font.heavySystemFont(FAMILY === "small" ? 34 : 44), COLORS.text);',
		'  hero.addSpacer(6);',
		'  const heroLabel = hero.addStack();',
		'  heroLabel.layoutVertically();',
		'  heroLabel.addSpacer();',
		'  addText(heroLabel, label, Font.boldSystemFont(11), COLORS.muted);',
		'  addText(heroLabel, "streak", Font.boldSystemFont(11), COLORS.muted);',
		'  hero.addSpacer();',
		'  addPill(hero, statusText, color);',
		'}',
		'',
		'function addRoutineRow(container, routine, cache, settings) {',
		'  const row = container.addStack();',
		'  row.layoutHorizontally();',
		'  row.centerAlignContent();',
		'  row.backgroundColor = new Color(COLORS.card, 0.62);',
		'  row.cornerRadius = 9;',
		'  row.setPadding(7, 9, 7, 9);',
		'',
		'  const name = addText(row, routine.label || routine.id, Font.mediumSystemFont(11), COLORS.text);',
		'  name.minimumScaleFactor = 0.75;',
		'  row.addSpacer();',
		'  addPill(row, routineScheduleTypeLabel(settings, routine), COLORS.accent);',
		'  row.addSpacer(6);',
		'  addText(row, String(cache.currentStreak || 0) + "d", Font.boldSystemFont(11), COLORS.muted);',
		'  row.addSpacer(6);',
		'  addPill(row, routineStatusPillLabel(settings, routine, cache), statusColor(cache.todayStatus));',
		'}',
		'',
		'function routineGridVisibleCount(routines) {',
		'  if (FAMILY === "small") return 1;',
		'  if (FAMILY === "medium") return Math.min(routines.length, MAX_ROUTINES);',
		'  return Math.min(routines.length, MAX_ROUTINES);',
		'}',
		'',
		'function routineCardColumns(visibleCount) {',
		'  if (FAMILY === "small") return 1;',
		'  if (FAMILY === "medium") return Math.max(1, visibleCount);',
		'  return 2;',
		'}',
		'',
		'function routineCardSize(visibleCount) {',
		'  if (FAMILY === "small") return new Size(0, 98);',
		'  if (FAMILY === "medium") {',
		'    if (visibleCount >= 4) return new Size(68, 94);',
		'    if (visibleCount === 3) return new Size(92, 94);',
		'    return new Size(132, 94);',
		'  }',
		'  return new Size(132, 94);',
		'}',
		'',
		'function compactStatusLabel(status) {',
		'  if (status === "complete") return "Done";',
		'  if (status === "incomplete") return "Open";',
		'  if (status === "missing_daily_note") return "Missing";',
		'  if (status === "no_tasks") return "None";',
		'  if (status === "frozen") return "Frozen";',
		'  if (status === "off_schedule") return "Rest";',
		'  if (status === "stale") return "Sync";',
		'  return "Idle";',
		'}',
		'',
		'function addStatusDot(container, status) {',
		'  const dot = container.addStack();',
		'  dot.size = new Size(8, 8);',
		'  dot.cornerRadius = 4;',
		'  dot.backgroundColor = new Color(statusColor(status));',
		'}',
		'',
		'function addRoutineGridCard(container, routine, cache, visibleCount, settings) {',
		'  const card = container.addStack();',
		'  card.layoutVertically();',
		'  card.backgroundColor = new Color(COLORS.card, cache.todayStatus === "off_schedule" ? 0.42 : 0.72);',
		'  card.borderWidth = 1;',
		'  card.borderColor = new Color(statusColor(cache.todayStatus), cache.todayStatus === "off_schedule" ? 0.42 : 0.72);',
		'  card.cornerRadius = 11;',
		'  card.size = routineCardSize(visibleCount);',
		'  card.setPadding(8, FAMILY === "medium" && visibleCount >= 4 ? 7 : 9, 8, FAMILY === "medium" && visibleCount >= 4 ? 7 : 9);',
		'',
		'  const header = card.addStack();',
		'  header.layoutHorizontally();',
		'  header.centerAlignContent();',
		'  const title = addText(header, routine.label || routine.id, Font.boldSystemFont(11), cache.todayStatus === "off_schedule" ? COLORS.muted : COLORS.text);',
		'  title.minimumScaleFactor = 0.65;',
		'  header.addSpacer(4);',
		'  addPill(header, routineScheduleTypeLabel(settings, routine), COLORS.accent);',
		'  card.addSpacer(5);',
		'',
		'  const body = card.addStack();',
		'  body.layoutHorizontally();',
		'  body.bottomAlignContent();',
		'  addText(body, String(cache.currentStreak || 0), Font.heavySystemFont(24), COLORS.text);',
		'  body.addSpacer(3);',
		'  addText(body, "d", Font.boldSystemFont(10), COLORS.muted);',
		'  body.addSpacer();',
		'  if (FAMILY === "medium") {',
		'    addStatusDot(body, cache.todayStatus);',
		'  } else {',
		'    addPill(body, compactStatusLabel(cache.todayStatus), statusColor(cache.todayStatus));',
		'  }',
		'',
		'  card.addSpacer(5);',
		'  const progress = cache.todayStatus === "stale" ? "Open Obsidian" : routineProgressLabel(settings, routine, cache);',
		'  addText(card, progress, Font.systemFont(9), COLORS.muted);',
		'}',
		'',
		'function addRoutineCardGrid(container, routines, settings) {',
		'  const visible = routines.slice(0, routineGridVisibleCount(routines));',
		'  const columns = routineCardColumns(visible.length);',
		'  const spacing = FAMILY === "medium" && visible.length >= 4 ? 6 : 8;',
		'',
		'  for (let index = 0; index < visible.length; index += columns) {',
		'    const row = container.addStack();',
		'    row.layoutHorizontally();',
		'    row.centerAlignContent();',
		'    row.addSpacer();',
		'    const rowRoutines = visible.slice(index, index + columns);',
		'',
		'    for (let column = 0; column < rowRoutines.length; column += 1) {',
		'      const routine = rowRoutines[column];',
		'      addRoutineGridCard(row, routine, cacheFor(settings, routine), visible.length, settings);',
		'',
		'      if (column < rowRoutines.length - 1) {',
		'        row.addSpacer(spacing);',
		'      }',
		'    }',
		'',
		'    row.addSpacer();',
		'',
		'    if (index + columns < visible.length) {',
		'      container.addSpacer(8);',
		'    }',
		'  }',
		'}',
		'',
		'function addTaskRow(container, task) {',
		'  const row = container.addStack();',
		'  row.layoutHorizontally();',
		'  row.centerAlignContent();',
		'  row.setPadding(2, 0, 2, 0);',
		'  addText(row, task.completed ? "\\u2713" : "\\u25CB", Font.boldSystemFont(10), task.completed ? COLORS.success : COLORS.faint);',
		'  row.addSpacer(6);',
		'  const label = addText(row, task.text || "Untitled task", Font.systemFont(10), task.completed ? COLORS.faint : COLORS.text);',
		'  label.minimumScaleFactor = 0.7;',
		'}',
		'',
		'function addEmptyMessage(container, message) {',
		'  const card = container.addStack();',
		'  card.layoutVertically();',
		'  card.backgroundColor = new Color(COLORS.card, 0.58);',
		'  card.cornerRadius = 10;',
		'  card.setPadding(10, 10, 10, 10);',
		'  const text = addText(card, message, Font.systemFont(11), COLORS.muted);',
		'  text.lineLimit = 3;',
		'}',
		'',
		'function addMetrics(widget, summary, routines) {',
		'  const metrics = widget.addStack();',
		'  metrics.layoutHorizontally();',
		'  addMetricCard(metrics, summary.completed + "/" + summary.requiredCount, "today", summary.allDone ? COLORS.success : COLORS.warning);',
		'  metrics.addSpacer(8);',
		'  addMetricCard(metrics, routines.length, "routines", COLORS.accent);',
		'}',
		'',
		'function overviewMetrics(settings, routines) {',
		'  const summary = todaySummary(settings);',
		'  return {',
		'    summary: summary,',
		'    metrics: [',
		'      { value: bestCurrentStreak(settings), label: "best", color: COLORS.text },',
		'      { value: summary.completed + "/" + summary.requiredCount, label: "today", color: summary.allDone ? COLORS.success : COLORS.warning },',
		'      { value: routines.length, label: "routines", color: COLORS.accent },',
		'    ],',
		'  };',
		'}',
		'',
		'function addOverviewMetricRow(container, metrics, size) {',
		'  const row = container.addStack();',
		'  row.layoutHorizontally();',
		'  row.centerAlignContent();',
		'  row.addSpacer();',
		'',
		'  for (let index = 0; index < metrics.length; index += 1) {',
		'    const metric = metrics[index];',
		'    addMetricCard(row, metric.value, metric.label, metric.color, size);',
		'',
		'    if (index < metrics.length - 1) {',
		'      row.addSpacer(8);',
		'    }',
		'  }',
		'',
		'  row.addSpacer();',
		'}',
		'',
		'function createSetupWidget(message) {',
		'  const widget = new ListWidget();',
		'  setWidgetBackground(widget);',
		'  widget.setPadding(16, 16, 16, 16);',
		'  addText(widget, "Routine Streaks", Font.boldSystemFont(15), COLORS.text);',
		'  widget.addSpacer(8);',
		'  const body = addText(widget, message, Font.systemFont(11), COLORS.muted);',
		'  body.lineLimit = 6;',
		'  return widget;',
		'}',
		'',
		'function createDashboardWidget(settings, routines) {',
		'  const summary = todaySummary(settings);',
		'  const statusText = summary.requiredCount === 0 ? "Rest day" : summary.completed + "/" + summary.requiredCount + " done today";',
		'  const widget = createBaseWidget(settings, "Routine Streaks", summary.allDone ? "Today is clear" : "Still in progress", summary.allDone);',
		'',
		'  addHeroStreak(widget, bestCurrentStreak(settings), "best", statusText, summary.allDone ? COLORS.success : COLORS.warning);',
		'',
		'  if (FAMILY !== "small") {',
		'    widget.addSpacer(10);',
		'    addMetrics(widget, summary, routines);',
		'    widget.addSpacer(10);',
		'    const visible = routines.slice(0, MAX_ROUTINES);',
		'    for (const routine of visible) {',
		'      addRoutineRow(widget, routine, cacheFor(settings, routine), settings);',
		'      widget.addSpacer(4);',
		'    }',
		'  }',
		'',
		'  if (FAMILY === "large") {',
		'    widget.addSpacer();',
		'    const computed = routines.map(function (routine) {',
		'      return cacheFor(settings, routine).lastComputedAt || "";',
		'    }).filter(Boolean).sort().pop() || "Never";',
		'    addText(widget, "Updated " + computed.slice(0, 16).replace("T", " "), Font.systemFont(9), COLORS.faint);',
		'  }',
		'',
		'  return widget;',
		'}',
		'',
		'function createOverviewWidget(settings, routines) {',
		'  const overview = overviewMetrics(settings, routines);',
		'  const summary = overview.summary;',
		'  const widget = createBaseWidget(settings, "Overview", summary.allDone ? "Today is clear" : "Still in progress", summary.allDone, false);',
		'',
		'  if (FAMILY === "large") {',
		'    widget.addSpacer();',
		'    const petRow = widget.addStack();',
		'    petRow.layoutHorizontally();',
		'    petRow.addSpacer();',
		'    addPetImage(petRow, settings, summary.allDone, 108);',
		'    petRow.addSpacer();',
		'    widget.addSpacer(14);',
		'    addOverviewMetricRow(widget, overview.metrics, new Size(86, 64));',
		'    widget.addSpacer();',
		'    return widget;',
		'  }',
		'',
		'  const row = widget.addStack();',
		'  row.layoutHorizontally();',
		'  row.centerAlignContent();',
		'  addPetImage(row, settings, summary.allDone, 42);',
		'  row.addSpacer(8);',
		'  for (let index = 0; index < overview.metrics.length; index += 1) {',
		'    const metric = overview.metrics[index];',
		'    addMetricCard(row, metric.value, metric.label, metric.color, new Size(62, 60));',
		'    if (index < overview.metrics.length - 1) row.addSpacer(6);',
		'  }',
		'',
		'  return widget;',
		'}',
		'',
		'function createPetWidget(settings, routines) {',
		'  const summary = todaySummary(settings);',
		'  const widget = createBaseWidget(settings, "Routine pet", summary.allDone ? "Happy today" : "Needs attention", summary.allDone, false);',
		'  widget.addSpacer();',
		'  const pet = widget.addStack();',
		'  pet.layoutVertically();',
		'  pet.centerAlignContent();',
		'  addPetImage(pet, settings, summary.allDone, FAMILY === "small" ? 58 : FAMILY === "medium" ? 92 : 118);',
		'  pet.addSpacer(8);',
		'  const statusText = summary.requiredCount === 0 ? "Rest day" : summary.completed + "/" + summary.requiredCount + " done today";',
		'  addPill(pet, statusText, summary.allDone ? COLORS.success : COLORS.warning);',
		'  widget.addSpacer();',
		'  return widget;',
		'}',
		'',
		'function createRoutineCardsWidget(settings, routines) {',
		'  const summary = todaySummary(settings);',
		'  const widget = createBaseWidget(settings, "Routine cards", summary.allDone ? "Today is clear" : "Still in progress", summary.allDone);',
		'',
		'  if (routines.length === 0) {',
		'    addEmptyMessage(widget, "No enabled routines.");',
		'    return widget;',
		'  }',
		'',
		'  widget.addSpacer();',
		'  addRoutineCardGrid(widget, routines, settings);',
		'  widget.addSpacer();',
		'',
		'  return widget;',
		'}',
		'',
		'function todayItemCardSize() {',
		'  if (FAMILY === "small") return new Size(0, 112);',
		'  if (FAMILY === "medium") return new Size(132, 76);',
		'  return new Size(132, 116);',
		'}',
		'',
		'function addTodayItemGridCard(container, routine, cache, settings) {',
		'  const card = container.addStack();',
		'  card.layoutVertically();',
		'  card.backgroundColor = new Color(COLORS.card, cache.todayStatus === "off_schedule" ? 0.42 : 0.72);',
		'  card.borderWidth = 1;',
		'  card.borderColor = new Color(statusColor(cache.todayStatus), cache.todayStatus === "off_schedule" ? 0.42 : 0.72);',
		'  card.cornerRadius = 11;',
		'  card.size = todayItemCardSize();',
		'  card.setPadding(8, 9, 8, 9);',
		'',
		'  const header = card.addStack();',
		'  header.layoutHorizontally();',
		'  header.centerAlignContent();',
		'  const title = addText(header, routine.label || routine.id, Font.boldSystemFont(10), COLORS.text);',
		'  title.minimumScaleFactor = 0.65;',
		'  header.addSpacer();',
		'  addPill(header, routineScheduleTypeLabel(settings, routine), COLORS.accent);',
		'',
		'  card.addSpacer(4);',
		'  addText(card, cache.todayStatus === "stale" ? "Open Obsidian" : routineProgressLabel(settings, routine, cache), Font.systemFont(9), COLORS.muted);',
		'',
		'  const taskLimit = FAMILY === "large" ? 3 : FAMILY === "medium" ? 1 : 4;',
		'  const tasks = (cache.todayTasks || []).slice(0, taskLimit);',
		'',
		'  if (tasks.length > 0) {',
		'    card.addSpacer(4);',
		'  }',
		'',
		'  for (const task of tasks) {',
		'    addTaskRow(card, task);',
		'  }',
		'}',
		'',
		'function addTodayItemGrid(container, routines, settings) {',
		'  const visible = selectedTodayRoutines(settings, routines);',
		'',
		'  if (visible.length === 0) {',
		'    addEmptyMessage(container, "No selected routine tasks today.");',
		'    return;',
		'  }',
		'',
		'  const columns = FAMILY === "small" ? 1 : 2;',
		'',
		'  for (let index = 0; index < visible.length; index += columns) {',
		'    const row = container.addStack();',
		'    row.layoutHorizontally();',
		'    row.centerAlignContent();',
		'    row.addSpacer();',
		'    const rowRoutines = visible.slice(index, index + columns);',
		'',
		'    for (let column = 0; column < rowRoutines.length; column += 1) {',
		'      const routine = rowRoutines[column];',
		'      addTodayItemGridCard(row, routine, cacheFor(settings, routine), settings);',
		'      if (column < rowRoutines.length - 1) row.addSpacer(8);',
		'    }',
		'',
		'    row.addSpacer();',
		'    if (index + columns < visible.length) container.addSpacer(8);',
		'  }',
		'}',
		'',
		'function createTodayItemsWidget(settings, routines) {',
		'  const summary = todaySummary(settings);',
		'  const widget = createBaseWidget(settings, "Today items", summary.allDone ? "All done" : "Open items", summary.allDone);',
		'  widget.addSpacer();',
		'  addTodayItemGrid(widget, routines, settings);',
		'  widget.addSpacer();',
		'  return widget;',
		'}',
		'',
		'function createRoutineFocusWidget(settings, routines) {',
		'  const summary = todaySummary(settings);',
		'  const routine = selectedRoutine(settings, routines);',
		'',
		'  if (!routine) {',
		'    const widget = createBaseWidget(settings, "Routine Streaks", "No enabled routines", summary.allDone);',
		'    addEmptyMessage(widget, "No enabled routines.");',
		'    return widget;',
		'  }',
		'',
		'  const cache = cacheFor(settings, routine);',
		'  const widget = createBaseWidget(settings, routine.label || routine.id, statusLabel(cache.todayStatus), cache.todayStatus === "complete");',
		'  addHeroStreak(widget, cache.currentStreak || 0, "current", routineStatusPillLabel(settings, routine, cache), statusColor(cache.todayStatus));',
		'  widget.addSpacer(10);',
		'  const meta = widget.addStack();',
		'  meta.layoutHorizontally();',
		'  addPill(meta, routineScheduleTypeLabel(settings, routine), COLORS.accent);',
		'  meta.addSpacer(6);',
		'  const tag = addText(meta, routine.tag || "", Font.systemFont(9), COLORS.muted);',
		'  tag.minimumScaleFactor = 0.7;',
		'',
		'  return widget;',
		'}',
		'',
		'function createWidget(settings) {',
		'  const routines = enabledRoutines(settings);',
		'  const type = selectedWidgetType(settings);',
		'',
		'  if (type === "overview") return createOverviewWidget(settings, routines);',
		'  if (type === "pet") return createPetWidget(settings, routines);',
		'  if (type === "routine_cards") return createRoutineCardsWidget(settings, routines);',
		'  if (type === "today_items") return createTodayItemsWidget(settings, routines);',
		'  if (type === "routine_focus") return createRoutineFocusWidget(settings, routines);',
		'  return createDashboardWidget(settings, routines);',
		'}',
		'',
		'const settings = await readRoutineSettings();',
		'const widget = settings.error ? createSetupWidget(settings.error) : createWidget(settings);',
		'',
		'if (config.runsInWidget) {',
		'  Script.setWidget(widget);',
		'} else if (FAMILY === "large") {',
		'  await widget.presentLarge();',
		'} else if (FAMILY === "small") {',
		'  await widget.presentSmall();',
		'} else {',
		'  await widget.presentMedium();',
		'}',
		'',
		'Script.complete();',
	].join('\n');
}
